### ISSUE TITLE
docTR half precision 

### ISSUE THREAD

**Issue by felixdittrich92** [clamsproject/app-doctr-wrapper#1]
### Because

Hi @snewman-aa 👋 
Only a short note:

If you already require a GPU you can run the whole `ocr_predictor` in full half precision with `.half()` after moving to cuda device which provides an large speedup and memory footprint reduction :)

https://github.com/clamsproject/app-doctr-wrapper/blob/0dbd3f07b9deb755f79f0fc663262c91f8eeb199/app.py#L43

**Comment by snewman-aa** [comment]
Thank you @felixdittrich92 !
